services:
  dev:
    # This is the 'remote' name and the 'local' name
    image: ghcr.io/ahmed-zamouche/ucli:latest

    # This allows you to build locally
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    privileged: true
    volumes:
      - .:/workspace/cli
    working_dir: /workspace/cli
    command: tail -f /dev/null
